
objs += \
	  $(ROOT)/apps/$(APP_CASE)/aec/$(CPU)/audio_aec.o \
	  $(ROOT)/apps/$(APP_CASE)/aec/$(CPU)/audio_aec_dms.o \
	  $(ROOT)/apps/$(APP_CASE)/aec/$(CPU)/audio_aec_online.o \

includes += \
	-I$(ROOT)/cpu/$(CPU)/ \
