

objs += \
	$(ROOT)/apps/common/device/gx8002_npu/gx8002_npu.o \
	$(ROOT)/apps/common/device/gx8002_npu/gx8002_npu_event_deal.o \
	$(ROOT)/apps/common/device/gx8002_npu/gx8002_upgrade/gx_uart_upgrade.o \
	$(ROOT)/apps/common/device/gx8002_npu/gx8002_upgrade/gx_uart_upgrade_porting.o \
	$(ROOT)/apps/common/device/gx8002_npu/gx8002_upgrade/sdfile_upgrade/gx_uart_upgrade_sdfile.o \
	$(ROOT)/apps/common/device/gx8002_npu/gx8002_upgrade/spp_upgrade/gx_uart_upgrade_spp.o \
	$(ROOT)/apps/common/device/gx8002_npu/gx8002_upgrade/spp_upgrade/gx_fifo.o \
